spring:
  datasource:
    url: jdbc:mariadb://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_SCHEMA}?characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none