spring:
  datasource:
    url: jdbc:mariadb://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_SCHEMA}?characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length:
        access: ${JWT_EXPIRATION_DURATION}

cloud:
  aws:
    s3.bucket: ${S3_BUCKET_NAME}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    endpoint: ${S3_END_POINT}

gpt:
  api-key: ${GPT_API_KEY}