spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      jdbc:
        time-zone: Asia/Seoul
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 150MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length:
        access: 604800000
        refresh: 604600000

cloud:
  aws:
    s3.bucket: ${S3_BUCKET}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    endpoint: ${S3_END_POINT}

gpt:
  api-key: ${GPT_ACCESS_KEY}

sentry:
  dsn: ${SENTRY_DNS}
  traces-sample-rate: 1.0