server:
  shutdown: graceful
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active:
      - ${ACTIVE_PROFILE}
  web:
    resources:
      add-mappings: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'