FROM docker.io/library/openjdk:17
ENV ACTIVE_PROFILE=${ACTIVE_PROFILE}
COPY ../build/libs/meommuapi-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=${ACTIVE_PROFILE}", "-jar", "/app.jar"]