version: '3'

services:
  meommu-db:
    container_name: meommu-db
    image: mariadb
    environment:
      MYSQL_DATABASE: meommu
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volume/mariadb/data:/var/lib/mysql # migration
      - ./docker-volume/mariadb/config:/etc/mysql/conf.d # migration
    restart: always
    networks:
      - meommu_network

  blue:
    container_name: blue
    image: jdi0222/meommu
    ports:
      - 8081:8080
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_END_POINT: ${S3_END_POINT}
      GPT_API_KEY: ${GPT_API_KEY}
    depends_on:
      - meommu-db
    networks:
      - meommu_network

  green:
    container_name: green
    image: jdi0222/meommu
    ports:
      - 8082:8080
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_END_POINT: ${S3_END_POINT}
      GPT_API_KEY: ${GPT_API_KEY}
    depends_on:
      - meommu-db
    networks:
      - meommu_network

networks:
  meommu_network:
    driver: bridge