version: '3'

services:
  blue:
    container_name: blue
    image: jdi0222/meommu
    ports:
      - 8081:8080

  green:
    container_name: green
    image: jdi0222/meommu
    ports:
      - 8082:8080
