version: '3'

services:
  blue:
    container_name: blue
    image: jdi0222/meommu
    ports:
      - 8081:8080
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_END_POINT: ${S3_END_POINT}
      GPT_API_KEY: ${GPT_API_KEY}

  green:
    container_name: green
    image: jdi0222/meommu
    ports:
      - 8082:8080
    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_END_POINT: ${S3_END_POINT}
      GPT_API_KEY: ${GPT_API_KEY}