version: '3'

services:
  meommu-db:
    container_name: meommu-db
    image: mariadb
    environment:
      MYSQL_DATABASE: meommu
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volume/mariadb/data:/var/lib/mysql # migration
      - ./docker-volume/mariadb/config:/etc/mysql/conf.d # migration
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - meommu_network

  blue:
    container_name: blue
    image: jdi0222/meommu
    ports:
      - 8081:8080
    depends_on:
      - meommu-db
    networks:
      - meommu_network

  green:
    container_name: green
    image: jdi0222/meommu
    ports:
      - 8082:8080
    depends_on:
      - meommu-db
    networks:
      - meommu_network

networks:
  meommu_network:
    driver: bridge