name: Deploy Main to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: meomu/meommu-api
          stage: main
          yaml: |
            name: meommu-api
            app: java@17
            options:
              ports: 8080
              env:
                - name: RDS_ENDPOINT
                  value: ${{ secrets.RDS_ENDPOINT }}
                - name: RDS_PORT
                  value: ${{ secrets.RDS_PORT }}
                - name: RDS_SCHEMA
                  value: ${{ secrets.RDS_SCHEMA }}
                - name: RDS_USERNAME
                  value: ${{ secrets.RDS_USERNAME }}
                - name: RDS_PASSWORD
                  value: ${{ secrets.RDS_PASSWORD }}
                - name: JWT_SECRET_KEY
                  value: ${{ secrets.JWT_SECRET_KEY }}
                - name: JWT_EXPIRATION_DURATION
                  value: ${{ secrets.JWT_EXPIRATION_DURATION }} 
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}