name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository to VM
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Environment
        run: echo "${{ secrets.PROD_ENV_PROPERTIES }}" > ./.env

      - name: Create Mysql Docker Container
        run: sudo docker run -d -p 3305:3306 --env MYSQL_DATABASE="test" --env MYSQL_ROOT_PASSWORD="test" mysql:8.0.31

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build